### ISSUE TITLE
quotes not rendering in test wrapper logging output

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/ibmcloud-terratest-wrapper#871]
Looks like the quotes are not rendering in the output:

`2024/09/27 20:06:13 Error creating config from JSON: Error retrieving from catalog: Catalog &quot;7df1e4ca-d54c-4fd0-82ce-3d13247308cd&quot; not found in account &quot;abac0df06b644a9cabc6e44f55b3880e&quot;`

full log: https://github.com/terraform-ibm-modules/dev-rag/actions/runs/11076936943/job/30781254140

**Comment by daniel-butler-irl** [comment]
This is the exact message from the service, they are returning raw HTML. I don't think we want to render HTML in the logs?

**Comment by ocofaigh** [comment]
@daniel-butler-irl which service is this? And what api are we calling?

**Comment by daniel-butler-irl** [comment]
Closing for now the logger has been enhanced since, and we do not have control of the output. I think this is probably from Schematics and I think you might even see it locally when running in Terraform. It would need a deepdive and I don't think its that important...
